# Generated by Django 4.0.dev20210914135008 on 2021-10-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_alter_message_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
